(load "streams.rkt")

(define (print-m matrix)
  (display "[")
  (stream-print (head matrix)) (newline)
  (stream-for-each (lambda (x) (display " ")
                     (stream-print x) (newline))
                   (tail matrix))
  (display "]\n"))

(define (prune stream n)
  (define (hulp stream i doorlaten?)
    (cond ((empty-stream? stream) the-empty-stream)
          ((>= i n) (hulp stream 0 (not doorlaten?)))
          (doorlaten? (cons-stream (head stream)
                                   (hulp (tail stream)
                                   (+ i 1)
                                   doorlaten?)))
    (else (hulp (tail stream) (+ i 1) doorlaten?))))
  (hulp stream 0 #t))

; iter
(define (split stream n)
  (define (splitter stream res i)
    (cond ((or (empty-stream? stream) (= i n))
           (cons (apply stream-values (reverse res))
                 stream))
          (else (splitter (tail stream)
                          (cons (head stream) res)
                          (+ i 1)))))
  (if (empty-stream? stream)
     the-empty-stream
     (let ((tmp (splitter stream '() 0)))
       (cons-stream (car tmp)
                    (split (cdr tmp) n)))))

(define (nachtgemiddelden s)
  (stream-map (lambda (s)
                (let ((x (stream-accumulate (lambda (a b)
                                              (cons (+ a (car b)) (+ 1 (cdr b))))
                                            (cons 0 0)
                                            s)))
                   (exact->inexact (/ (car x) (cdr x)))))
   (prune (tail (split s 12)) 1)))

(define temperaturen (enumerate-int 1 48))
(stream-print (nachtgemiddelden temperaturen))