(define (my-append e l)
  (define (iter lst res)
    (if (null? lst)
        res
        (iter (cdr lst)
              (cons (car lst)
                   res)
              )
        )
    )
  (iter (reverse e) l)
  )