(define (super-merge-n lsts n)
  (define (merge current rest i)
    (cond ((and (null? current) (null? rest)) '())
          ((null? current) (merge (car rest) (cdr rest) 0))
          ((= i n) (merge (car rest)
                          (append (cdr rest) (list current)) 0))
          (else (cons (car current) (merge (cdr current) rest (+ i 1))))))
  (if (null? lsts)
      '()
      (merge (car lsts) (cdr lsts) 0)))

(super-merge-n '((a b c d e f)
                   (g h i j k)
                   (l m n o p q)
                   (r s t u v w))
                 3)